plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace "com.genesys.shape"
    compileSdk 36

    defaultConfig {
        minSdk 23
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.constraintlayout
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.impeterwayne'
                artifactId = 'ShapeView'
                version = '1.0.1'
            }
        }
    }
}
